报这个错：  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)

解决方案：

```py
import sys
stdi,stdo,stde=sys.stdin,sys.stdout,sys.stderr
reload(sys)
sys.stdin,sys.stdout,sys.stderr=stdi,stdo,stde
sys.setdefaultencoding('utf-8')
```
